### ISSUE TITLE
Pente Fino - Link para o Site da Brasa no Rodape

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/quinta-essentia#22]
Faltou nas imagens o Link para o site da Brasa e do WordPress (pt-br) no Rodape do Site:

![image](https://cloud.githubusercontent.com/assets/5949986/8640348/df7bbe1c-28ba-11e5-819b-f7b2e847319d.png)

Talvez colocar a seguinte frase: "Feito em [WordPress] pela [Brasa]." -> Onde o que esta entre [ ] seria os logos que ja estao la..

**Comment by willowmagrini** [comment]
@LuwkasLima da uma olhada lá e me fala o que acha.

**Comment by LuwkasLima** [comment]
Belezura! Eu so acho que a frase "Criado em" fica mais interessante do que "Criado com"...sei lah!

Outra coisa, deixaria o icone do Creative Commons do lado Direito ou Esquerdo, com o texto ajustado do lado da imagem, quase como tava antes, so que com o texto ajustado pro lado da imagem:

![image](https://cloud.githubusercontent.com/assets/5949986/8658738/4aa82ed6-296b-11e5-8fd3-a648cf255c2d.png)

**Comment by LuwkasLima** [comment]
Falta o link do site do WordPress tbm: http://br.wordpress.org/

@diegorojas e @everaldomatias verifiquem voces tambem pra ver se precisamos diminuir um pouco a fonte e as imagens, me parecem um pouquinho exagerados. Mas utilizem seu olho artistico..

Vlw @willowmagrini !

**Comment by LuwkasLima** [comment]
Por mim esse aqui ta fechado..
