### ISSUE TITLE
Pente Fino - Menu do MIDIA nao muda para ingles

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/quinta-essentia#25]
Tem alguma configuracao que o cara tem que fazer pra habilitar o Menu da area de Midia pra ficar em ingles?

![image](https://cloud.githubusercontent.com/assets/5949986/8640428/6c4d6ffa-28bd-11e5-8810-d837cd2afcb6.png)

**Comment by LuwkasLima** [comment]
mesma coisa nos titulos da area Social:

![image](https://cloud.githubusercontent.com/assets/5949986/8640429/ada5a882-28bd-11e5-9db0-c30a9290eb76.png)

**Comment by LuwkasLima** [comment]
E botoes de enviar...rs

**Comment by willowmagrini** [comment]
Tudo ok
